# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5 # Supply chain protection: prevent rapid updates

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 5 # Supply chain protection: general update frequency control
      semver-major-days: 30 # Major version updates require extended review
      semver-minor-days: 7 # Minor version updates get moderate delay
      semver-patch-days: 3 # Patch updates (security fixes) get minimal delay
    ignore:
      - dependency-name: "@vitest/browser"